name: golden_goblin
description: A brief yet powerful money manager.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+20211124

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^5.0.2
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^3.4.0
  shared_preferences: ^2.0.8
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
